services:

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#     - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
    environment:
      - GLANCES_OPT=-w
      - TZ=Europe/Madrid
    ports:
      - "8888:61208"
    pid: host
    restart: unless-stopped
